version: 2.1
jobs:
  test-full-ruby27:
    docker:
      - image: cimg/ruby:2.7-node
      - image: cimg/mysql:8.0
        command: [--default-authentication-plugin=mysql_native_password]
        environment:
          MYSQL_ROOT_HOST: '%'
          MYSQL_ROOT_PASSWORD: 'root'
          MYSQL_DATABASE: 'qpixel_test'
      - image: cimg/redis:7.0

    working_directory: ~/qpixel

    steps:
      - run:
          name: Install packages
          command: |
            sudo apt-get --allow-releaseinfo-change -qq update
            sudo apt-get -y install git libmariadb-dev libmagickwand-dev
      - checkout
      - restore_cache:
          keys:
            - qpixel-{{ checksum "Gemfile.lock" }}
            - qpixel-
      - run:
          name: Install Bundler & gems
          command: |
            gem install bundler
            bundle install --path=~/gems
      - save_cache:
          key: qpixel-{{ checksum "Gemfile.lock" }}
          paths:
            - ~/gems
      - run:
          name: Copy key
          command: |
            echo "$MASTER_KEY" > config/master.key
      - run:
          name: Prepare config & database
          environment:
            RAILS_ENV: test
          command: |
            cp config/database.sample.yml config/database.yml
            cp config/storage.sample.yml config/storage.yml
            bundle exec rails db:create
            bundle exec rails db:schema:load
            bundle exec rails db:migrate
            bundle exec rails test:prepare
      - run:
          name: Current revision
          command: |
            git rev-parse $(git rev-parse --abbrev-ref HEAD)
      - run:
          name: Coveralls token
          command: |
            echo "repo_token: $COVERALLS_REPO_TOKEN" > .coveralls.yml
      - run:
          name: Test
          command: |
            bundle exec rails test
      - store_test_results:
          path: "~/qpixel/test/reports"

  test-full-ruby30:
    docker:
      - image: cimg/ruby:3.0-node
      - image: cimg/mysql:8.0
        command: [ --default-authentication-plugin=mysql_native_password ]
        environment:
          MYSQL_ROOT_HOST: '%'
          MYSQL_ROOT_PASSWORD: 'root'
          MYSQL_DATABASE: 'qpixel_test'
      - image: cimg/redis:7.0

    working_directory: ~/qpixel

    steps:
      - run:
          name: Install packages
          command: |
            sudo apt-get --allow-releaseinfo-change -qq update
            sudo apt-get -y install git libmariadb-dev libmagickwand-dev
      - checkout
      - restore_cache:
          keys:
            - qpixel-{{ checksum "Gemfile.lock" }}
            - qpixel-
      - run:
          name: Install Bundler & gems
          command: |
            gem install bundler
            bundle install --path=~/gems
      - save_cache:
          key: qpixel-{{ checksum "Gemfile.lock" }}
          paths:
            - ~/gems
      - run:
          name: Copy key
          command: |
            echo "$MASTER_KEY" > config/master.key
      - run:
          name: Prepare config & database
          environment:
            RAILS_ENV: test
          command: |
            cp config/database.sample.yml config/database.yml
            cp config/storage.sample.yml config/storage.yml
            bundle exec rails db:create
            bundle exec rails db:schema:load
            bundle exec rails db:migrate
            bundle exec rails test:prepare
      - run:
          name: Current revision
          command: |
            git rev-parse $(git rev-parse --abbrev-ref HEAD)
      - run:
          name: Coveralls token
          command: |
            echo "repo_token: $COVERALLS_REPO_TOKEN" > .coveralls.yml
      - run:
          name: Test
          command: |
            bundle exec rails test
      - store_test_results:
          path: "~/qpixel/test/reports"

  test-full-ruby31:
    docker:
      - image: cimg/ruby:3.1-node
      - image: cimg/mysql:8.0
        command: [ --default-authentication-plugin=mysql_native_password ]
        environment:
          MYSQL_ROOT_HOST: '%'
          MYSQL_ROOT_PASSWORD: 'root'
          MYSQL_DATABASE: 'qpixel_test'
      - image: cimg/redis:7.0

    working_directory: ~/qpixel

    steps:
      - run:
          name: Install packages
          command: |
            sudo apt-get --allow-releaseinfo-change -qq update
            sudo apt-get -y install git libmariadb-dev libmagickwand-dev
      - checkout
      - restore_cache:
          keys:
            - qpixel-{{ checksum "Gemfile.lock" }}
            - qpixel-
      - run:
          name: Install Bundler & gems
          command: |
            gem install bundler
            bundle install --path=~/gems
      - save_cache:
          key: qpixel-{{ checksum "Gemfile.lock" }}
          paths:
            - ~/gems
      - run:
          name: Copy key
          command: |
            echo "$MASTER_KEY" > config/master.key
      - run:
          name: Prepare config & database
          environment:
            RAILS_ENV: test
          command: |
            cp config/database.sample.yml config/database.yml
            cp config/storage.sample.yml config/storage.yml
            bundle exec rails db:create
            bundle exec rails db:schema:load
            bundle exec rails db:migrate
            bundle exec rails test:prepare
      - run:
          name: Current revision
          command: |
            git rev-parse $(git rev-parse --abbrev-ref HEAD)
      - run:
          name: Coveralls token
          command: |
            echo "repo_token: $COVERALLS_REPO_TOKEN" > .coveralls.yml
      - run:
          name: Test
          command: |
            bundle exec rails test
      - store_test_results:
          path: "~/qpixel/test/reports"

  test-ruby27:
    docker:
      - image: cimg/ruby:2.7-node
      - image: cimg/mysql:8.0
        command: [--default-authentication-plugin=mysql_native_password]
        environment:
          MYSQL_ROOT_HOST: '%'
          MYSQL_ROOT_PASSWORD: 'root'
          MYSQL_DATABASE: 'qpixel_test'
      - image: cimg/redis:7.0

    working_directory: ~/qpixel

    steps:
      - run:
          name: Install packages
          command: |
            sudo apt-get --allow-releaseinfo-change -qq update
            sudo apt-get -y install git libmariadb-dev libmagickwand-dev
      - checkout
      - restore_cache:
          keys:
            - qpixel-{{ checksum "Gemfile.lock" }}
            - qpixel-
      - run:
          name: Install Bundler & gems
          command: |
            gem install bundler
            bundle install --path=~/gems
      - save_cache:
          key: qpixel-{{ checksum "Gemfile.lock" }}
          paths:
            - ~/gems
      - run:
          name: Prepare config & database
          environment:
            RAILS_ENV: test
          command: |
            cp config/database.sample.yml config/database.yml
            cp config/storage.sample.yml config/storage.yml
            rm config/credentials.yml.enc
            bundle exec rails db:create
            bundle exec rails db:schema:load
            bundle exec rails db:migrate
            bundle exec rails test:prepare
      - run:
          name: Current revision
          command: |
            git rev-parse $(git rev-parse --abbrev-ref HEAD)
      - run:
          name: Test
          environment:
            SKIP_STRIPE: true
          command: |
            bundle exec rails test
      - store_test_results:
          path: "~/qpixel/test/reports"

  test-ruby30:
    docker:
      - image: cimg/ruby:3.0-node
      - image: cimg/mysql:8.0
        command: [ --default-authentication-plugin=mysql_native_password ]
        environment:
          MYSQL_ROOT_HOST: '%'
          MYSQL_ROOT_PASSWORD: 'root'
          MYSQL_DATABASE: 'qpixel_test'
      - image: cimg/redis:7.0

    working_directory: ~/qpixel

    steps:
      - run:
          name: Install packages
          command: |
            sudo apt-get --allow-releaseinfo-change -qq update
            sudo apt-get -y install git libmariadb-dev libmagickwand-dev
      - checkout
      - restore_cache:
          keys:
            - qpixel-{{ checksum "Gemfile.lock" }}
            - qpixel-
      - run:
          name: Install Bundler & gems
          command: |
            gem install bundler
            bundle install --path=~/gems
      - save_cache:
          key: qpixel-{{ checksum "Gemfile.lock" }}
          paths:
            - ~/gems
      - run:
          name: Prepare config & database
          environment:
            RAILS_ENV: test
          command: |
            cp config/database.sample.yml config/database.yml
            cp config/storage.sample.yml config/storage.yml
            rm config/credentials.yml.enc
            bundle exec rails db:create
            bundle exec rails db:schema:load
            bundle exec rails db:migrate
            bundle exec rails test:prepare
      - run:
          name: Current revision
          command: |
            git rev-parse $(git rev-parse --abbrev-ref HEAD)
      - run:
          name: Test
          environment:
            SKIP_STRIPE: true
          command: |
            bundle exec rails test
      - store_test_results:
          path: "~/qpixel/test/reports"

  test-ruby31:
    docker:
      - image: cimg/ruby:3.1-node
      - image: cimg/mysql:8.0
        command: [ --default-authentication-plugin=mysql_native_password ]
        environment:
          MYSQL_ROOT_HOST: '%'
          MYSQL_ROOT_PASSWORD: 'root'
          MYSQL_DATABASE: 'qpixel_test'
      - image: cimg/redis:7.0

    working_directory: ~/qpixel

    steps:
      - run:
          name: Install packages
          command: |
            sudo apt-get --allow-releaseinfo-change -qq update
            sudo apt-get -y install git libmariadb-dev libmagickwand-dev
      - checkout
      - restore_cache:
          keys:
            - qpixel-{{ checksum "Gemfile.lock" }}
            - qpixel-
      - run:
          name: Install Bundler & gems
          command: |
            gem install bundler
            bundle install --path=~/gems
      - save_cache:
          key: qpixel-{{ checksum "Gemfile.lock" }}
          paths:
            - ~/gems
      - run:
          name: Prepare config & database
          environment:
            RAILS_ENV: test
          command: |
            cp config/database.sample.yml config/database.yml
            cp config/storage.sample.yml config/storage.yml
            rm config/credentials.yml.enc
            bundle exec rails db:create
            bundle exec rails db:schema:load
            bundle exec rails db:migrate
            bundle exec rails test:prepare
      - run:
          name: Current revision
          command: |
            git rev-parse $(git rev-parse --abbrev-ref HEAD)
      - run:
          name: Test
          environment:
            SKIP_STRIPE: true
          command: |
            bundle exec rails test
      - store_test_results:
          path: "~/qpixel/test/reports"

  rubocop:
    docker:
      - image: cimg/ruby:3.1-node

    working_directory: ~/qpixel

    steps:
      - run:
          name: Install packages
          command: |
            sudo apt-get --allow-releaseinfo-change -qq update
            sudo apt-get -y install git libmariadb-dev libmagickwand-dev
      - checkout
      - restore_cache:
          keys:
            - qpixel-{{ checksum "Gemfile.lock" }}
            - qpixel-
      - run:
          name: Install Bundler & gems
          command: |
            gem install bundler
            bundle install --path=~/gems
      - save_cache:
          key: qpixel-{{ checksum "Gemfile.lock" }}
          paths:
            - ~/gems
      - run:
          name: Rubocop
          command: |
            bundle exec rubocop

  deploy:
    docker:
      - image: cimg/ruby:2.7-node

    working_directory: ~/qpixel

    steps:
      - run:
          name: Import SSH key
          command: |
            echo "$DEV_SSH_KEY" | base64 --decode > ~/deploy.key
            chmod 0700 ~/deploy.key
      - run:
          name: Run deploy
          command: |
            ssh -o 'StrictHostKeyChecking no' "$SSH_USER"@"$SSH_IP" -p "$SSH_PORT" -i ~/deploy.key "sudo su -l qpixel /var/apps/deploy-dev"

workflows:
  test_lint:
    jobs:
      - test-ruby27:
          filters:
            branches:
              ignore: develop
      - test-ruby30:
          filters:
            branches:
              ignore: develop
      - test-ruby31:
          filters:
            branches:
              ignore: develop
      - test-full-ruby27:
          filters:
            branches:
              only: develop
      - test-full-ruby30:
          filters:
            branches:
              only: develop
      - test-full-ruby31:
          filters:
            branches:
              only: develop
      - rubocop
      - deploy:
          requires:
            - test-full-ruby27
            - test-full-ruby30
            - test-full-ruby31
            - rubocop
          filters:
            branches:
              only: develop
